
name: Generate coverage report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Bacondish2023/setup-googletest@v1
      with:
        tag: v1.14.0

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DBUILD_UNIT_TESTS=OFF -DBUILD_COVERAGE=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Debug

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C Debug

    - name: Upload coverage report to codecov
      uses: codecov/codecov-action@v4
      with:
        file: build/coverage.xml
        working-directory: ${{github.workspace}}
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
